from etl_ap import etl_ap #Librería desarrollada por Elico
from datetime import datetime
import pytz
import json
import requests
from time import sleep
import snap7
import struct
import csv
from snap7.exceptions import Snap7Exception
from requests.exceptions import RequestException

variables = [
        "timestamp",
        "energia_total",
        "gas_total",
        "producto_1_total",
        "producto_2_total",
        "producto_3_total",
        "unidades_totales",
        "batch_identificador_batch",
        "batch_control",
        "batch_batch_iniciado",
        "batch_batch_finalizado",
        "batch_fala_presente",
        "batch_referencia",
        "batch_unidades_referencia",
        "batch_unidades_procesadas",
        "batch_unidades_empacadas",
        "batch_unidades_rechazadas_procesamiento",
        "batch_unidades_rechazadas_empaque",
        "batch_unidades_terminadas_incorrectamente",
        "batch_unidades_producidas",
        "batch_produccion_estandar",
        "batch_energia_referencia",
        "batch_energia_consumida",
        "batch_energia_estandar",
        "batch_gas_referencia",
        "batch_gas_consumida",
        "batch_gas_estandar",
        "batch_producto_1_referencia",
        "batch_producto_2_referencia",
        "batch_producto_3_referencia",
        "batch_producto_1_consumido",
        "batch_producto_2_consumido",
        "batch_producto_3_consumido",
        "batch_tiempo_referencia",
        "batch_tiempo_efectivo",
        "batch_tiempo_inactivo",
        "batch_tiempo_total",
        "batch_tiempo_umero_fallas",
        "batch_fallas_0_falla_activa",
        "batch_fallas_0_tipo_falla",
        "batch_fallas_0_control",
        "batch_fallas_0_tiempo_inactividad",
        "batch_fallas_0_energia_consumida",
        "batch_fallas_0_gas_consumida",
        "batch_fallas_1_falla_activa",
        "batch_fallas_1_tipo_falla",
        "batch_fallas_1_control",
        "batch_fallas_1_tiempo_inactividad",
        "batch_fallas_1_energia_consumida",
        "batch_fallas_1_gas_consumida",
        "batch_fallas_2_falla_activa",
        "batch_fallas_2_tipo_falla",
        "batch_fallas_2_control",
        "batch_fallas_2_tiempo_inactividad",
        "batch_fallas_2_energia_consumida",
        "batch_fallas_2_gas_consumida",
        "batch_fallas_3_falla_activa",
        "batch_fallas_3_tipo_falla",
        "batch_fallas_3_control",
        "batch_fallas_3_tiempo_inactividad",
        "batch_fallas_3_energia_consumida",
        "batch_fallas_3_gas_consumida",
        "batch_fallas_4_falla_activa",
        "batch_fallas_4_tipo_falla",
        "batch_fallas_4_control",
        "batch_fallas_4_tiempo_inactividad",
        "batch_fallas_4_energia_consumida",
        "batch_fallas_4_gas_consumida",
        "batch_fallas_5_falla_activa",
        "batch_fallas_5_tipo_falla",
        "batch_fallas_5_control",
        "batch_fallas_5_tiempo_inactividad",
        "batch_fallas_5_energia_consumida",
        "batch_fallas_5_gas_consumida",
        "batch_fallas_6_falla_activa",
        "batch_fallas_6_tipo_falla",
        "batch_fallas_6_control",
        "batch_fallas_6_tiempo_inactividad",
        "batch_fallas_6_energia_consumida",
        "batch_fallas_6_gas_consumida",
        "batch_fallas_7_falla_activa",
        "batch_fallas_7_tipo_falla",
        "batch_fallas_7_control",
        "batch_fallas_7_tiempo_inactividad",
        "batch_fallas_7_energia_consumida",
        "batch_fallas_7_gas_consumida",
        "batch_fallas_8_falla_activa",
        "batch_fallas_8_tipo_falla",
        "batch_fallas_8_control",
        "batch_fallas_8_tiempo_inactividad",
        "batch_fallas_8_energia_consumida",
        "batch_fallas_8_gas_consumida",
        "batch_fallas_9_falla_activa",
        "batch_fallas_9_tipo_falla",
        "batch_fallas_9_control",
        "batch_fallas_9_tiempo_inactividad",
        "batch_fallas_9_energia_consumida",
        "batch_fallas_9_gas_consumida",
]

etl = etl_ap.etl_ap(
    ip='192.168.20.50', 
    rack=0, slot=0, name='PLC_1500', 
    route_log='/home/oem/Desktop/etl.log', 
    url_api="https://andinapack-jamesgarcia.pythonanywhere.com/data/api/StagingArea/",
    token='2f03066de356534f8e74e0aba38559d5508e860a',
    variables=variables,
    db=1,
)

etl.run()